apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tacos-vs-burritos-
spec:
  arguments:
    parameters:
    - name: tenant-id
    - name: service-principal-id
    - name: service-principal-password
    - name: subscription-id
    - name: resource-group
    - name: workspace
    - name: persistent-volume-name
      value: azure
    - name: persistent-volume-path
      value: /mnt/azure
    - name: data-download
      value: https://centeotl.blob.core.windows.net/public/tacodata.zip
    - name: epochs
      value: '5'
    - name: batch
      value: '32'
    - name: learning-rate
      value: '0.0001'
    - name: imagetag
      value: latest
    - name: model-name
      value: tacosandburritos
  entrypoint: tacos-vs-burritos
  serviceAccountName: pipeline-runner
  templates:
  - container:
      args:
      - /scripts/data.py
      - --base_path
      - '{{inputs.parameters.persistent-volume-path}}'
      - --data
      - train
      - --target
      - train.txt
      - --img_size
      - '160'
      - --zipfile
      - '{{inputs.parameters.data-download}}'
      command:
      - python
      image: kfamlacr.azurecr.io/kubeflow/preprocess:{{inputs.parameters.imagetag}}
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /mnt/azure
        name: azure
    inputs:
      parameters:
      - name: data-download
      - name: imagetag
      - name: persistent-volume-path
    name: preprocess
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
  - container:
      args:
      - /scripts/register.py
      - --base_path
      - '{{inputs.parameters.persistent-volume-path}}'
      - --model
      - latest.h5
      - --model_name
      - '{{inputs.parameters.model-name}}'
      - --tenant_id
      - '{{inputs.parameters.tenant-id}}'
      - --service_principal_id
      - '{{inputs.parameters.service-principal-id}}'
      - --service_principal_password
      - '{{inputs.parameters.service-principal-password}}'
      - --subscription_id
      - '{{inputs.parameters.subscription-id}}'
      - --resource_group
      - '{{inputs.parameters.resource-group}}'
      - --workspace
      - '{{inputs.parameters.workspace}}'
      command:
      - python
      image: kfamlacr.azurecr.io/kubeflow/register:{{inputs.parameters.imagetag}}
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /mnt/azure
        name: azure
    inputs:
      parameters:
      - name: imagetag
      - name: model-name
      - name: persistent-volume-path
      - name: resource-group
      - name: service-principal-id
      - name: service-principal-password
      - name: subscription-id
      - name: tenant-id
      - name: workspace
    name: register
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: data-download
            value: '{{inputs.parameters.data-download}}'
          - name: imagetag
            value: '{{inputs.parameters.imagetag}}'
          - name: persistent-volume-path
            value: '{{inputs.parameters.persistent-volume-path}}'
        name: preprocess
        template: preprocess
      - arguments:
          parameters:
          - name: imagetag
            value: '{{inputs.parameters.imagetag}}'
          - name: model-name
            value: '{{inputs.parameters.model-name}}'
          - name: persistent-volume-path
            value: '{{inputs.parameters.persistent-volume-path}}'
          - name: resource-group
            value: '{{inputs.parameters.resource-group}}'
          - name: service-principal-id
            value: '{{inputs.parameters.service-principal-id}}'
          - name: service-principal-password
            value: '{{inputs.parameters.service-principal-password}}'
          - name: subscription-id
            value: '{{inputs.parameters.subscription-id}}'
          - name: tenant-id
            value: '{{inputs.parameters.tenant-id}}'
          - name: workspace
            value: '{{inputs.parameters.workspace}}'
        dependencies:
        - training
        name: register
        template: register
      - arguments:
          parameters:
          - name: batch
            value: '{{inputs.parameters.batch}}'
          - name: epochs
            value: '{{inputs.parameters.epochs}}'
          - name: imagetag
            value: '{{inputs.parameters.imagetag}}'
          - name: learning-rate
            value: '{{inputs.parameters.learning-rate}}'
          - name: persistent-volume-path
            value: '{{inputs.parameters.persistent-volume-path}}'
        dependencies:
        - preprocess
        name: training
        template: training
    inputs:
      parameters:
      - name: batch
      - name: data-download
      - name: epochs
      - name: imagetag
      - name: learning-rate
      - name: model-name
      - name: persistent-volume-path
      - name: resource-group
      - name: service-principal-id
      - name: service-principal-password
      - name: subscription-id
      - name: tenant-id
      - name: workspace
    name: tacos-vs-burritos
  - container:
      args:
      - /scripts/train.py
      - --base_path
      - '{{inputs.parameters.persistent-volume-path}}'
      - --data
      - train
      - --epochs
      - '{{inputs.parameters.epochs}}'
      - --batch
      - '{{inputs.parameters.batch}}'
      - --image_size
      - '160'
      - --lr
      - '{{inputs.parameters.learning-rate}}'
      - --outputs
      - model
      - --dataset
      - train.txt
      command:
      - python
      image: kfamlacr.azurecr.io/kubeflow/training:{{inputs.parameters.imagetag}}
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /mnt/azure
        name: azure
    inputs:
      parameters:
      - name: batch
      - name: epochs
      - name: imagetag
      - name: learning-rate
      - name: persistent-volume-path
    name: training
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: azure-managed-disk
